// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh2INViHJh0_YgXS2StTXpz9oo2nHyZcM',
    appId: '1:555289903220:android:1b873c9b89ffaf1dc59121',
    messagingSenderId: '555289903220',
    projectId: 'openponic-mvp',
    storageBucket: 'openponic-mvp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK3lEDFjYXFqet4Cfts0BSe7eW4P31heQ',
    appId: '1:555289903220:ios:8e768d4da11fffc5c59121',
    messagingSenderId: '555289903220',
    projectId: 'openponic-mvp',
    storageBucket: 'openponic-mvp.appspot.com',
    iosClientId: '555289903220-v7t91j3snu42e197apfkl5fa7aq4daqk.apps.googleusercontent.com',
    iosBundleId: 'br.dev.yago.openponic',
  );
}
